export const APP_INITIALIZATION = 'APP_INITIALIZATION'
export const APP_INITIALIZATION_SUCCESS = 'APP_INITIALIZATION_SUCCESS'
export const APP_INITIALIZATION_FAILED = 'APP_INITIALIZATION_FAILED'
export const APP_INITIALIZATION_RESTORE_SETTINGS = 'APP_INITIALIZATION_RESTORE_SETTINGS'

export const APP_COMPILATION_SET_COMPILATION_SCRIPTS = 'APP_COMPILATION_SET_SCRIPTS'

export const APP_COMPILATION_START_COMPILATION = 'APP_COMPILATION_START_COMPILATION'
export const APP_COMPILATION_START_COMPILATION_SCRIPT_START = 'APP_COMPILATION_START_COMPILATION_SCRIPT_START'
export const APP_COMPILATION_START_COMPILATION_SCRIPT_SUCCESS = 'APP_COMPILATION_START_COMPILATION_SCRIPT_SUCCESS'
export const APP_COMPILATION_START_COMPILATION_SCRIPT_FAILED = 'APP_COMPILATION_START_COMPILATION_SCRIPT_FAILED'
export const APP_COMPILATION_START_COMPILATION_FINISH = 'APP_COMPILATION_START_COMPILATION_FINISH'

export const APP_COMPILATION_LOGS_SET_LOGS = 'APP_COMPILATION_LOGS_SET_LOGS'
export const APP_COMPILATION_LOGS_POPUP_TOGGLE = 'APP_COMPILATION_LOGS_POPUP_TOGGLE'

export const APP_GROUPS_ADD_GROUP = 'APP_GROUPS_ADD_GROUP'
export const APP_GROUPS_EDIT_GROUP = 'APP_GROUPS_EDIT_GROUP'
export const APP_GROUPS_REMOVE_GROUP = 'APP_GROUPS_REMOVE_GROUP'
export const APP_GROUPS_SAVE_GROUPS = 'APP_GROUPS_SAVE_GROUPS'
export const APP_GROUPS_SAVE_GROUPS_TO_LOCAL = 'APP_GROUPS_SAVE_GROUPS_TO_LOCAL'

export const APP_SETTINGS_SET_GAME_FOLDER = 'APP_SETTINGS_SET_GAME_FOLDER'
export const APP_SETTINGS_SET_USE_MO2 = 'APP_SETTINGS_SET_USE_MO2'
export const APP_SETTINGS_SET_MO2_INSTANCE = 'APP_SETTINGS_SET_MO2_INSTANCE'
export const APP_SETTINGS_SET_GAME = 'APP_SETTINGS_SET_GAME'
export const APP_SETTINGS_DETECT_SOURCES_FOLDERS = 'APP_SETTINGS_DETECT_SOURCES_FOLDERS'
export const APP_SETTINGS_SET_DETECTED_SOURCES_FOLDERS = 'APP_SETTINGS_SET_DETECTED_SOURCES_FOLDERS'
export const APP_SETTINGS_DETECT_SOURCES_FOLDERS_SUCCESS = 'APP_SETTINGS_DETECT_SOURCES_FOLDERS_SUCCESS'
export const APP_SETTINGS_DETECT_SOURCES_FOLDERS_FAILED = 'APP_SETTINGS_DETECT_SOURCES_FOLDERS_FAILED'

export const APP_CHANGELOG_GET_LATEST_NOTES = 'APP_CHANGELOG_GET_LATEST_NOTES'
export const APP_CHANGELOG_GET_LATEST_NOTES_SUCCESS = 'APP_CHANGELOG_GET_LATEST_NOTES_SUCCESS'
export const APP_CHANGELOG_GET_LATEST_NOTES_FAILED = 'APP_CHANGELOG_GET_LATEST_NOTES_FAILED'
export const APP_CHANGELOG_SET_LATEST_VERSION = 'APP_CHANGELOG_SET_LATEST_VERSION'
export const APP_CHANGELOG_SET_SHOW_NOTES = 'APP_CHANGELOG_SET_SHOW_NOTES'

export const APP_SETTINGS_DETECT_BAD_INSTALLATION = 'APP_SETTINGS_DETECT_BAD_INSTALLATION'
export const APP_SETTINGS_DETECT_BAD_INSTALLATION_SUCCESS = 'APP_SETTINGS_DETECT_BAD_INSTALLATION_SUCCESS'
export const APP_SETTINGS_DETECT_BAD_INSTALLATION_FAILED = 'APP_SETTINGS_DETECT_BAD_INSTALLATION_FAILED'

export const APP_TASK_LOADING_SET = 'APP_TASK_LOADING_SET'

export const APP_ERROR_CLEAN = 'APP_ERROR_CLEAN'
export const APP_ERROR_CLEAN_SELECTED = 'APP_ERROR_CLEAN_SELECTED'

export const APP_LOG_OPEN = 'APP_LOG_OPEN'
