# This is a basic workflow to help you get started with Actions

name: Automatic build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: []
  pull_request:
    branches: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: egordm/gha-yarn-node-cache@v1

    # Runs a single command using the runners shell
    - name: Setup Node.js
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 10.18.0
    - name: Dependencies
      run: yarn --network-timeout 100000
    - name: Build
      run: yarn package
   - name: Upload node_modules
     uses: actions/upload-artifact@v2.1.4
     with:
       # Artifact name
       name: node_modules
       # A file, directory or wildcard pattern that describes what to upload
       path: node_modules
       # The desired beha
    - name: Upload artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: |
          build-le
          build-se
        # The desired beha

