name: CI

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.mjs'
      - '**.tsx'
      - '**.yml'
      - '**.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          run_install: true

      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: 'pnpm'

      - run: pnpm lint
      - run: pnpm build
