name: CI

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.mjs'
      - '**.tsx'
      - '**.yml'
      - '**.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.3
        id: pnpm-cache-ubuntu
        with:
          path: '**/node_modules'
          key: "${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}"
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.16

      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.18.3
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
