name: CI

on:
  push:
    paths:
      - '**.ts'
      - '**.js'
      - '**.mjs'
      - '**.tsx'
      - '**.yml'
      - '**.yaml'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm lint
      - run: pnpm fmt:check
      - run: pnpm build
