name: Generate release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.15

      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.16.0
          run_install: true

      - name: Generate SE
        env:
          ELECTRON_WEBPACK_APP_MOD_URL: https://www.nexusmods.com/skyrimspecialedition/mods/23852
        run: |
          pnpm build
          pnpm package -- --config.productName="PCA SE" --config.extraMetadata.name="PCA SE"

      - name: Generate LE
        env:
          ELECTRON_WEBPACK_APP_MOD_URL: https://www.nexusmods.com/skyrim/mods/96339
        run: |
          pnpm build -- --no-clean
          pnpm package

      - uses: actions/create-release@v1
        id: create_release
        name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: PCA ${{ github.ref }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA LE.7z'
          asset_name: PCA LE.7z

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA LE.Setup.exe'
          asset_name: PCA LE.Setup.exe

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA SE.Setup.exe'
          asset_name: PCA SE.Setup.exe

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA SE.7z'
          asset_name: PCA SE.7z
