name: Release

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  release:
    if: startsWith(github.head_ref, 'changeset-release')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Build
        run: pnpm build

      - name: Package
        env:
          ELECTRON_WEBPACK_APP_MOD_URL: https://www.nexusmods.com/skyrimspecialedition/mods/23852
          ELECTRON_TELEMETRY_API_KEY: ''
          ELECTRON_TELEMETRY_API: ''
          ELECTRON_TELEMETRY_FEATURE: false
        run: pnpm package

      - name: Create Release Pull Request
        uses: changesets/action@v1
        id: changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          createGithubReleases: false
          commit: 'chore(release): update version for release'
          title: 'chore(release): update version for release'
          version: 'pnpm changeset:version'

      #      - uses: actions/create-release@v1
      #        id: create_release
      #        if: success()
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        with:
      #          tag_name: ${{ github.ref }}
      #          release_name: PCA ${{ github.ref }}
      #          draft: true
      #          body: ${{ steps.extract_changelog.outputs.content }}
      #          prerelease: false

      - uses: actions/upload-release-asset@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA LE.7z'
          asset_name: PCA LE.7z
          asset_content_type: application/x-7z-compressed

      - uses: actions/upload-release-asset@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/PCA SE.7z'
          asset_name: PCA SE.7z
          asset_content_type: application/x-7z-compressed
