# This is a basic workflow to help you get started with Actions

name: Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: egordm/gha-yarn-node-cache@v1

      # Runs a single command using the runners shell
      - name: Setup Node.js
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 10.18.0
      - name: 'Download build artifact'
        uses: actions/download-artifact@v2.0.5
        with:
          name: 'build'
      - name: Dependencies
        run: yarn --network-timeout 100000
      - name: Package
        run: yarn package --package --zip
      - name: Upload packages
        uses: actions/upload-artifact@v2.1.4
        with:
          # Artifact name
          name: papyrus-compiler
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            papyrus-compiler-le.7z
            papyrus-compiler-se.7z
          # The desired beha

