name: Package

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.3
        id: pnpm-cache-windows
        with:
          path: '**/node_modules'
          key: "${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}"

      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 14.15

      - name: Dependencies
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.15.2
          run_install: |
            - args: [--shamefully-hoist]

      - name: Generate SE
        run: |
          pnpm build
          pnpm package -- --config.productName="PCA SE" --config.extraMetadata.name="PCA SE"

      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: package-se
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/PCA*.7z

      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: setup-se
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/PCA*.exe

      - name: Generate LE
        run: |
          pnpm build
          pnpm package

      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: package-le
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/PCA*.7z

      - uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: setup-le
          # A file, directory or wildcard pattern that describes what to upload
          path: dist/PCA*.exe
