name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node_modules

      - name: Setup Node.js
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 10.18.0

      - name: Dependencies
        run: yarn --network-timeout 100000

      - name: 'Download package'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: package.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: papyrus-compiler

      - name: Create Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
